### ISSUE TITLE
saveAll() do nothing. Did I miss something ? 

### ISSUE THREAD

**Issue by mgodeneche** [bytefish/JSqlServerBulkInsert#13]
Helllo! 
Well this project could be very usefull for me so I tried to implement it. 

Here is my code 

```	
public void bulkInsert()  {
		log.info("Starting Bulk Insert ");
		Connection conn = null;
		
		try {
			LineMapping mapping = new Mapping();
			SqlServerBulkInsert<Line> bulkInsert = new SqlServerBulkInsert<>(mapping);
			conn = DatabaseTools.getConnection();
			log.info("Bulk size "+LinesToInsert.size());
			bulkInsert.saveAll(conn, stockLinesToInsert.stream());
			log.info(DatabaseTools.getTempRows()+" items inserted");
			conn.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}

	}
```

Giving me this output..... And nothing more.. 

```
 INFO 14996 --- [pool-2-thread-1] c.c.R.Application           : Starting Bulk Insert 
 INFO 14996 --- [pool-2-thread-1] c.c.R.Application           : Bulk size 47361

```

No errors,no logs..  obviously I tried to wait but after 5+ min I consider it's out of order. 
My table is still empty. 

I thought it was a bad mapping but all seems ok : 
```
public class LineMapping extends AbstractMapping<Line> {

	public LineMapping() {
        super("dbo", "MY_TABLE");

        /** somme mapping stuff like this, all compiling **/
	 mapNvarchar("Name", Line::getName);	
         mapInteger("Count", Line::getCount);     
    
    }
```

So , my ArrayList of items contains lot of object but the bulkInsert.saveAll() don't save them.. 

Any idea of what is going on ? I probably missed something but no way to find what.. 
I tried to use your example with Persons , it worked fine..

Thanks for your work and - I hope - for your help 😄

**Comment by vslee** [comment]
For the mapping, try creating a new new LineMapping(); instead of a new Mapping();

**Comment by mgodeneche** [comment]
Well after some test it seems if Table is misscreated ( bad varchar dimensionning i.e. ) error is not logged if you are in multi thread context. 
I moove some code for test purpose in my main() and i got instant error about my table column not large enought for some data.. 

Maybe this project deserve some custom exception raised in case of error ?

**Comment by vslee** [comment]
Yes, if you'd like to create a test case, or even better, send us a pull request, we will add it.

**Comment by mgodeneche** [comment]
I'll do it tomorow 👍

**Comment by bytefish** [comment]
Closed due to inactivity.
