### ISSUE TITLE
Not working with recent versions

### ISSUE THREAD

**Issue by jacky-lam** [bytefish/JSqlServerBulkInsert#14]
Hi,

I have tried to use your library for java 11, and experiencing some problems.

My code:
```
Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
String dbURL = "jdbc:sqlserver://localhost:1433;databaseName=test";
Properties properties = new Properties();
properties.put("user", "sa");
properties.put("password", "test");
Connection conn = DriverManager.getConnection(dbURL, properties);
SqlServerBulkInsert<MyObject> bulkInsert = new SqlServerBulkInsert<>(mappingObject);
bulkInsert.saveAll(conn, objects.stream());
```

My JDBC in pom.xml
```
        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <version>8.2.2.jre8</version>
        </dependency>
```

Error at runtime:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeToServer(com.microsoft.sqlserver.jdbc.ISQLServerBulkRecord)'
	at de.bytefish.jsqlserverbulkinsert.SqlServerBulkInsert.saveAll(SqlServerBulkInsert.java:40)
	at de.bytefish.jsqlserverbulkinsert.SqlServerBulkInsert.saveAll(SqlServerBulkInsert.java:27)
```
- Seems like there is an issue with the recent version?

**Comment by bytefish** [comment]
I have removed the deprecated ``ISqlServerBulkRecord`` and now implement the ``ISqlServerBulkData`` directly. The call to ``writeToServer`` in SQL Server JDBC driver version ``8.2.2.jre8`` now works correctly. 

The Version 3.0.0 of the Library has been released to the Maven Central Repositories and should be available within some hours, it always takes some time for the Maven Repositories to sync.

**Comment by bytefish** [comment]
Please let me know, if the issue is fixed once the new version is availbale in Maven. 👍

**Comment by bytefish** [comment]
@vslee I haven't had time to look into the Release Drafter Plugin to draft this Release. I am sorry, maybe you could add it to the repository?

**Comment by vslee** [comment]
I'll take care of the release notes.

**Comment by vslee** [comment]
The way Release Drafter works is that it will create a list of the pull requests that are merged. It categorizes them based on the label (bug, enhancement, maintenance). It doesn't list changes that are committed directly w/o a PR though. So if you make any big changes in the future that you'd like to automatically include in the changelogs, make them through a PR instead of committing directly. You can apply a label and then still immediately approve/merge the PR afterwards. 
(Since there are not that many updates to this project, I also don't mind creating the release changelogs manually from the commits.)

**Comment by bytefish** [comment]
@vslee Thanks, it's noted. Next time I will do a clean PR!

**Comment by jacky-lam** [comment]
Hi @bytefish 

Thank you for making a quick fix. I have tested and this is working!

Not necessary, but it might be helpful to include in the README that you must map *all* the fields in the table, otherwise it won't work (i.e. I omitted the auto-generated fields (e.g. triggers/auto-increments) and it didnt work 😛)

**Comment by bytefish** [comment]
@jacky-lam Maybe you could create a separate ticket and describe what's missing in the README. 👍

**Comment by jacky-lam** [comment]
https://github.com/bytefish/JSqlServerBulkInsert/issues/15
